services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=My@Test@Password1
    command:
      [
        "/opt/mssql/bin/sqlservr",
        "--accept-eula",
        "--reset-sa-password"
      ]

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  test_linux:
    build: .
    # Firing up the databases will take a while, fortunately so does compilating the library
    depends_on:
      - mssql
      - mariadb
      - postgres
    network_mode: host
    environment:
      RUST_LOG: DEBUG